apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiap-postgres-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fiap-postgres
  template:
    metadata:
      labels:
        app: fiap-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16.8-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: fiapdb
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: fiap-db-secret
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fiap-db-secret
                  key: DB_PASS
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          emptyDir: {}
