apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-fiap-01-service
spec:
  type: NodePort
  selector:
    app: tech-challenge-fiap-01
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
